# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZalDo4--qNGEJlhZxuC2XLjBNf8Xv8b
"""

from fastapi import FastAPI
from pydantic import BaseModel
import requests

app = FastAPI()

class Request(BaseModel):
    prompt: str

@app.get("/")
def home():
    return {"message": "AI Agent Running 🚀"}

@app.post("/chat")
def chat(req: Request):
    response = requests.post(
        "https://openrouter.ai/api/v1/chat/completions",
        headers={
            "Authorization": "Bearer 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",
            "Content-Type": "application/json"
        },
        json={
            "model": "openai/gpt-3.5-turbo",
            "messages": [{"role": "user", "content": req.prompt}]
        }
    )
    return response.json()